apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
data:
  config.json: |
    {
      "run_type": "server",
      "local_addr": "{{ .Values.trojan.config.server }}",
      "local_port": {{ .Values.trojan.config.port }},
      "password": {{ .Values.trojan.config.password | toJson }},
      "ssl": {
        "cert": "/etc/ssl/certs/cert.pem",
        "key": "/etc/ssl/private/key.pem"
      }
    }